# permissions for end users to edit horreum.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: horreum-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: horreum-operator
    app.kubernetes.io/part-of: horreum-operator
    app.kubernetes.io/managed-by: kustomize
  name: horreum-editor-role
rules:
- apiGroups:
  - hyperfoil.io
  resources:
  - horreums
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperfoil.io
  resources:
  - horreums/status
  verbs:
  - get
